"""added audio submit

Revision ID: 2efd2afce72c
Revises: 23dd26d7c029
Create Date: 2022-12-08 11:42:16.809690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2efd2afce72c'
down_revision = '23dd26d7c029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('artistname', sa.String(length=64), nullable=True),
    sa.Column('artistemail', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submit_artistemail'), ['artistemail'], unique=False)
        batch_op.create_index(batch_op.f('ix_submit_artistname'), ['artistname'], unique=False)
        batch_op.create_index(batch_op.f('ix_submit_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submit_title'))
        batch_op.drop_index(batch_op.f('ix_submit_artistname'))
        batch_op.drop_index(batch_op.f('ix_submit_artistemail'))

    op.drop_table('submit')
    # ### end Alembic commands ###
