"""added contacts

Revision ID: 36e8ec092520
Revises: 786a0a664d2f
Create Date: 2022-12-07 14:47:05.089374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e8ec092520'
down_revision = '786a0a664d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_name'))
        batch_op.drop_index(batch_op.f('ix_contact_email'))

    op.drop_table('contact')
    # ### end Alembic commands ###
