"""added datetime to submit

Revision ID: 58aeb724f9da
Revises: 5c7f56e33005
Create Date: 2022-12-08 14:38:00.040736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58aeb724f9da'
down_revision = '5c7f56e33005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_submit_datetime'), ['datetime'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submit_datetime'))
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###
