"""added audio trackname

Revision ID: 5c7f56e33005
Revises: 2efd2afce72c
Create Date: 2022-12-08 11:46:30.143199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7f56e33005'
down_revision = '2efd2afce72c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trackname', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_submit_trackname'), ['trackname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submit_trackname'))
        batch_op.drop_column('trackname')

    # ### end Alembic commands ###
