"""added Listen table

Revision ID: c749dcec43da
Revises: 58aeb724f9da
Create Date: 2022-12-11 09:55:26.573222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c749dcec43da'
down_revision = '58aeb724f9da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('artistname', sa.String(length=64), nullable=True),
    sa.Column('artistemail', sa.String(length=120), nullable=True),
    sa.Column('trackname', sa.String(length=120), nullable=True),
    sa.Column('albumart', sa.String(length=120), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listen_albumart'), ['albumart'], unique=False)
        batch_op.create_index(batch_op.f('ix_listen_artistemail'), ['artistemail'], unique=False)
        batch_op.create_index(batch_op.f('ix_listen_artistname'), ['artistname'], unique=False)
        batch_op.create_index(batch_op.f('ix_listen_datetime'), ['datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_listen_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_listen_trackname'), ['trackname'], unique=False)

    with op.batch_alter_table('submit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('albumart', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_submit_albumart'), ['albumart'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submit_albumart'))
        batch_op.drop_column('albumart')

    with op.batch_alter_table('listen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listen_trackname'))
        batch_op.drop_index(batch_op.f('ix_listen_title'))
        batch_op.drop_index(batch_op.f('ix_listen_datetime'))
        batch_op.drop_index(batch_op.f('ix_listen_artistname'))
        batch_op.drop_index(batch_op.f('ix_listen_artistemail'))
        batch_op.drop_index(batch_op.f('ix_listen_albumart'))

    op.drop_table('listen')
    # ### end Alembic commands ###
